from flask import Flask, escape, request
import os

application = Flask(__name__)

@application.route('/')
@application.route('/route-1')
@application.route('/route-2')
@application.route('/route-3')
@application.route('/route-4')
@application.route('/route-5')
@application.route('/route-6')
@application.route('/route-7')
@application.route('/route-8')
@application.route('/route-9')
@application.route('/route-10')
@application.route('/route-11')
@application.route('/route-12')
@application.route('/route-13')
@application.route('/route-14')
@application.route('/route-15')
@application.route('/route-16')
@application.route('/route-17')
@application.route('/route-18')
@application.route('/route-19')
@application.route('/route-20')
@application.route('/route-21')
@application.route('/route-22')
@application.route('/route-23')
@application.route('/route-24')
@application.route('/route-25')
@application.route('/route-26')
@application.route('/route-27')
@application.route('/route-28')
@application.route('/route-29')
@application.route('/route-30')
@application.route('/route-31')
@application.route('/route-32')
@application.route('/route-33')
@application.route('/route-34')
@application.route('/route-35')
@application.route('/route-36')
@application.route('/route-37')
@application.route('/route-38')
@application.route('/route-39')
@application.route('/route-40')
@application.route('/route-41')
@application.route('/route-42')
@application.route('/route-43')
@application.route('/route-44')
@application.route('/route-45')
@application.route('/route-46')
@application.route('/route-47')
@application.route('/route-48')
@application.route('/route-49')
@application.route('/route-50')
@application.route('/route-51')
@application.route('/route-52')
@application.route('/route-53')
@application.route('/route-54')
@application.route('/route-55')
@application.route('/route-56')
@application.route('/route-57')
@application.route('/route-58')
@application.route('/route-59')
@application.route('/route-60')
@application.route('/route-61')
@application.route('/route-62')
@application.route('/route-63')
@application.route('/route-64')
@application.route('/route-65')
@application.route('/route-66')
@application.route('/route-67')
@application.route('/route-68')
@application.route('/route-69')
@application.route('/route-70')
@application.route('/app2')
@application.route('/path1')
@application.route('/path1/subpath1')
@application.route('/path1/subpath2')
@application.route('/path1/subpath2/subsubpath1')
@application.route('/path1/subpath2/subsubpath1/subsubsubpath1')
def hello():
	app_name = os.environ.get('APP_NAME', 'Unable to get environment Value')
	return f'This response if from {app_name}'

@application.route('/stickyness')
def stickyness():
	pod_name = os.environ.get('POD_NAME', 'Unable to get environment Value')
	app_name = os.environ.get('APP_NAME', 'Unable to get environment Value')
	return f'{app_name} - This request is served by {pod_name}'

if __name__ == "__main__":
    application.run(host='0.0.0.0', port="80")
