apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dummy-app
  labels:
    app: "dummy"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "dummy"
  template:
    metadata:
      labels:
        app: "dummy"
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: app
          image: sairam546/flask-dummy-app:0.7
          args:
            - pipenv
            - run
            - gunicorn
            - --workers=5
            - -b
            - 0.0.0.0:8000
            - --log-level 
            - info
            - --access-logfile
            - "-"
            - wsgi
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: APP_NAME
              value: dummy-app
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: 0.1
              memory: 200Mi
            requests:
              cpu: 0.1
              memory: 200Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  name: flask-dummy-app
  labels:
    app: "dummy"
spec:
  selector:
      app: "dummy"
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer
